### ISSUE TITLE
还有一个问题

### ISSUE THREAD

**Issue by boom234567** [landuoguo/ewt360#10]
由于本人只有一点点（真的很少）py基础，所以请大佬多多指导。
当我打开ewt_crack_v2.0.2后。run module后出现以下字样：
= RESTART: C:\Users\Administrator\Downloads\ewt360-main\ewt360-main\ewt_crack_v2.0.2.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\ewt360-main\ewt360-main\ewt_crack_v2.0.2.py", line 17, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
请问是什么意思
感谢指导

**Comment by landuoguo** [comment]
需要安装第三方库，命令行执行pip install requests

**Comment by landuoguo** [comment]
其它的一些库你也要自己安装，不行可以查百度

**Comment by boom234567** [comment]
感谢

**Comment by boom234567** [comment]
似乎开始安装了

**Comment by boom234567** [comment]
命令行在下载了

**Comment by landuoguo** [comment]
建议使用清华源：pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by boom234567** [comment]
我试试

**Comment by boom234567** [comment]
命令行输入后出现
Writing to C:\Users\Administrator\AppData\Roaming\pip\pip.ini

**Comment by landuoguo** [comment]
这是正常的提示信息，建议以后有些小问题自己可以百度解决，自己百度也是一项技能

**Comment by boom234567** [comment]
抱歉给您添麻烦了。谢谢指导

**Comment by boom234567** [comment]
感谢大佬成功了

**Comment by boom234567** [comment]
我也出现此问题，而且既不显示已完成也不进行下一个。e网通但是完成了

**Comment by landuoguo** [comment]
由于本程序没有完备的时间计算机制，所以你只要放在那边等就行，程序过一段时间就会接下一个任务

**Comment by boom234567** [comment]
欧克
