### ISSUE TITLE
关于疑似BUG的反馈

### ISSUE THREAD

**Issue by EILCHINX** [landuoguo/ewt360#13]
感谢作者大大，在使用过程中，我发现ewt_gui_xxxx.exe和ewt_crack_xxxx.py都存在如果E网通账号分科后转过班级的话进行刷课刷的还是原来班级的课程。例如从物化生转到政史地那么刷的课程中还是原来包含物化生的课程，而政史地的课程则不会出现和被刷。

**Comment by EILCHINX** [comment]
感谢作者大大。我用了最新的wt_gui_1.3.3.exe发现这个BUG被修复了。感谢大大的更新维护！

**Comment by 2129716605** [comment]
作者大大，服务器连不上啊……
