### ISSUE TITLE
刷课失败反馈

### ISSUE THREAD

**Issue by xi-guang1** [landuoguo/ewt360#14]
用ewt_crack_v2.0.2.py刷课时，uploadprogress_v3函数仅第一次成功，之后返回{"success":false,"code":699001,"msg":"同学，系统监测您可能存在不良的学习行为，若继续此行为，后续看课时长将不再被统计","data":{"ts":*"eventId":"*"}}，重新运行程序仍只有第一次成功

**Comment by landuoguo** [comment]
ewt_crack_v2.0.2.py已停止维护，你可以使用GUI版本
