### ISSUE TITLE
如何获取license

### ISSUE THREAD

**Issue by BuGuoZheXie** [landuoguo/ewt360#15]
我实在不理解 license获取方法.txt里的获取方法，能不能更详细一点，感谢
![%K7OD)XHUEJWT$C{OG8K4 4](https://github.com/landuoguo/ewt360/assets/140884717/5d945912-0f28-466c-bdfd-ab86f1c6c3d9)

**Comment by landuoguo** [comment]
![QQ图片20230727223844](https://github.com/landuoguo/ewt360/assets/63572623/777ba0cf-99df-44cb-9110-6cf0a061ef4b)

**Comment by williamchen13** [comment]
这。。。。。
只得到一个时间戳错误
False timestamp
