### ISSUE TITLE
SDK 已经更到version 2.0.0了，失效

### ISSUE THREAD

**Issue by z0z0r4** [landuoguo/ewt360#2]
{"success":false,"code":699101,"msg":"当前会话已过期，请刷新页面重试","data":{"eventId":"db88ac96-9873-463e-ad2d-a92d70cc3610"}}

**Comment by landuoguo** [comment]
能把报错那个地方的错误信息给我看看吗？你这个错误信息只是会话过期的，可能是因为你在程序运行时登陆了网页版ewt或者同时运行多个刷课程序导致的

**Comment by natsurainko** [comment]
![DXO562051()21B_C~@} 4 O](https://user-images.githubusercontent.com/55646983/212802873-d1a685e4-5413-4257-98be-c30e1c507ccf.png)

![{`_KYE6C@QS4YTO1}70O%`9](https://user-images.githubusercontent.com/55646983/212802880-6ac4683e-63bb-45ce-8218-7648ac514b4e.png)

![AR5CKWL5ACU8MCL3E$QDM7S](https://user-images.githubusercontent.com/55646983/212802884-20f44b12-c9b4-4090-99a4-ad9539dd25e5.png)

如图 无论怎么请求均返回会话过期，不清楚是哪个地方的timestamp出了问题

**Comment by landuoguo** [comment]
你是尝试在用c＃重构代码吗？我今天早上测试我的程序还能用

**Comment by landuoguo** [comment]
你那个时间戳timestamp为什么会是13位的，我记得应该要是10位的

**Comment by z0z0r4** [comment]
> 
![image](https://user-images.githubusercontent.com/78744121/212814536-c8f4fb34-52b6-421b-8ac5-a0aa7caf081f.png)

XD，从js来看的话，确实已经变成13位ms为单位的了

**Comment by z0z0r4** [comment]
如果你看看现在的网页版的话，可以发现参数都全变了，可能只是1.0.0的SDK还能用...
![image](https://user-images.githubusercontent.com/78744121/212814709-629b5011-aa1e-4e99-99d9-a0a4c5c79992.png)
EventPackage 的参数变了...
![image](https://user-images.githubusercontent.com/78744121/212814756-5a67dddc-d69d-4852-baa7-22b274babd87.png)

> 你是尝试在用c＃重构代码吗？我今天早上测试我的程序还能用

**Comment by landuoguo** [comment]
可能ewt最近做了更新

**Comment by z0z0r4** [comment]
> 可能ewt最近做了更新

是这样的，刚好今天我们开始扒拉的时候就发现了

**Comment by landuoguo** [comment]
我程序里面还用了比1.0.0sdk还早的接口，还能用

**Comment by z0z0r4** [comment]
已经被恶心的不想动了...

**Comment by landuoguo** [comment]
ewt更新真的慢，几年前的接口还没被禁用

**Comment by z0z0r4** [comment]
指的是https://flog.ewt360.com/?sn=ewt_web_video_detail&log？

**Comment by landuoguo** [comment]
那个其实不是flog，是clog，只是我进行了一点魔改

**Comment by landuoguo** [comment]
哈哈

**Comment by z0z0r4** [comment]
看得出来，不过2.0.0的接口远比之前的初生 :(

**Comment by landuoguo** [comment]
2.0.0的代码好像ewt还没做混淆处理

**Comment by landuoguo** [comment]
我当时去扒1.0.0的贼恶心，全部被混淆了，弄了我一整天

**Comment by natsurainko** [comment]
![image](https://user-images.githubusercontent.com/55646983/212815680-8599d413-cf0c-4431-8931-ae213f3216fb.png)

![image](https://user-images.githubusercontent.com/55646983/212815730-7020ec87-c61d-4279-8843-56222f152b02.png)

![image](https://user-images.githubusercontent.com/55646983/212815777-61076f00-8b06-4aaa-85e1-7c0f1d11ecf0.png)

![6FE9@KV8Y25ML5%5G%}LE{H](https://user-images.githubusercontent.com/55646983/212815799-79e7a648-f4d8-420a-a909-8101f6bd7921.jpg)

**Comment by landuoguo** [comment]
我也没心思去研究新的接口，毕竟旧的还能用，而且我自己的课都刷完了

**Comment by landuoguo** [comment]
扒这些真是体力活

**Comment by z0z0r4** [comment]
> ![image](https://user-images.githubusercontent.com/55646983/212815680-8599d413-cf0c-4431-8931-ae213f3216fb.png)
> 
> ![image](https://user-images.githubusercontent.com/55646983/212815730-7020ec87-c61d-4279-8843-56222f152b02.png)
> 
> ![image](https://user-images.githubusercontent.com/55646983/212815777-61076f00-8b06-4aaa-85e1-7c0f1d11ecf0.png)
> 
> ![6FE9@KV8Y25ML5%5G%}LE{H](https://user-images.githubusercontent.com/55646983/212815799-79e7a648-f4d8-420a-a909-8101f6bd7921.jpg)
> 
> 

别倒腾了…fcdifftime和每个有关时间的参都绑定了…

**Comment by z0z0r4** [comment]
> 2.0.0的代码好像ewt还没做混淆处理

已经混淆的差不多了吧（？

**Comment by z0z0r4** [comment]
大佬方便加个QQ吗？太多疑问了.jpg
3531890582

**Comment by z0z0r4** [comment]
？
