### ISSUE TITLE
怎么运行啊

### ISSUE THREAD

**Issue by ivywangyihuan** [landuoguo/ewt360#4]
可以说一点都不懂，下载文件以后倒腾半天了一点都不会弄，怎么运行啊？要下载什么别的东西吗？是打开那个exe的还是py的啊？不好意思真的一点都不懂但是很需要帮助！

**Comment by ivywangyihuan** [comment]
可以发一个具体的步骤吗，每一步要干什么的那种？你说的很清晰但是可以再清晰一点吗？

**Comment by aurexare** [comment]
。。。你直接打开exe就行了啊
