### ISSUE TITLE
关于ewt的的batch接口无法跳课问题

### ISSUE THREAD

**Issue by SudoSuBash** [landuoguo/ewt360#7]
本人也是准高二,最近在和一个准高一一起重新研究ewt.
昨天晚上ewt的sdk更新了3.0.7,传统的batch大法貌似失效了.
我尝试用f12抓包， 然后把截下来的batch原封不动的搞到postman去研究,eventpackage中只换了关键的参数(包括stay_time),同时更改了加密后的signature,请求完后提示状态200,但是进度还是没有加.
还有自动填充选择题,我可以提供一个关键接口:https://web.ewt360.com/customerApi/api/studyprod/web/answer/submitanswer
请求方式为post,参数格式如下:
```javascript
{
            answers: answers,
            assignPoints: false,
            bizCode: bizCode.toString(),
            paperId: paperId.toString(),
            platform: "1",
            reportId: reportId.toString()
}
```

**Comment by landuoguo** [comment]
是的，我与今天早晨发现程序不可用。经多次尝试发现：batch的begin_time已经与x-bfe-session中的ts绑定，如果begin_time与x-bfe-session中的ts不一致看课进度将不增加。

**Comment by landuoguo** [comment]
目前速通的一条道路已经被封死。我们不能通过伪造虚假的begin_time来骗取时长，也就是说只能模拟真实的发包情况，60s发一个包

**Comment by landuoguo** [comment]
而且report_time不可以大于当前时间，否则也会被系统警告

**Comment by landuoguo** [comment]
速通目前我还想到另一个方法：手机端的离线看课进度上传接口可以利用，但本人懒得去弄了。我想模拟实际状况收发包时间是长了点，但也足够用了

**Comment by landuoguo** [comment]
已经更新

**Comment by FGonett** [comment]
有qq交流群？
