### ISSUE TITLE
2.0.2版本更新后无法自动

### ISSUE THREAD

**Issue by qq1161370434** [landuoguo/ewt360#8]
如题
具体情况为: 当一个课程完成后，程序并不会自动承接下一个程序，并且ewt360也只显示该课程完成并没有下一个课程的进度

**Comment by landuoguo** [comment]
说明：现在e网通无法速通，也就是说一个课程开始后要等这个课程时长的一半左右时间这个课程才能完成，这个课程完成后会自动接下一个课程的。如果还有什么bug请说明

**Comment by qq1161370434** [comment]
并不会,因为ewt360.com上提示已经完成并且重启该程序后承接下一个课程,并且我知道要等这个课程时长的一半左右时间这个课程才能完成

**Comment by landuoguo** [comment]
我想可能是因为你在刷的时候有登录网页版ewt，导致程序的cookie失效，所以无法完成下一个课程

**Comment by qq1161370434** [comment]
我重新试试

**Comment by qq1161370434** [comment]
登录手机端的不影响吧

**Comment by landuoguo** [comment]
手机端不影响

**Comment by qq1161370434** [comment]
我去测试了一下不登录网页端的情况下,也不会自动承接下一课程

**Comment by qq1161370434** [comment]
如果登录了网页端应该会报upload progress ERROR
{"success":false,"code":699001,"msg":"同学，一心勿多用，学累了，可以休息下，小e已为您自动暂停播放该视频","data":{"eventId":"1-64b8b9e7-da11d807eaa1dcfc27889d7b"}} 或者其他什么的

**Comment by landuoguo** [comment]
实在是令人感到疑惑

**Comment by landuoguo** [comment]
你qq多少，我加你

**Comment by qq1161370434** [comment]
3623213187
